"""Added relationships to the reviewtable

Revision ID: ccedd1881f03
Revises: 492fe670baaf
Create Date: 2024-02-12 20:51:58.551495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccedd1881f03'
down_revision = '492fe670baaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
